# Generated by Django 2.0 on 2019-08-23 13:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigClassTheme',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20, verbose_name='创建人')),
                ('updator', models.CharField(default='not', max_length=20, verbose_name='修改人')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit_timestamp', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_show', models.SmallIntegerField(choices=[(1, '显示'), (2, '隐藏')], default=1, verbose_name='页面展示')),
                ('bct_name', models.CharField(max_length=15, verbose_name='大类主题名')),
                ('bct_describe', models.TextField(default='此大类主题暂无描述', max_length=500, verbose_name='主题描述')),
            ],
            options={
                'verbose_name': '1-大类主题',
                'verbose_name_plural': '1-大类主题',
            },
        ),
        migrations.CreateModel(
            name='QuestionCalssTheme',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20, verbose_name='创建人')),
                ('updator', models.CharField(default='not', max_length=20, verbose_name='修改人')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit_timestamp', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_show', models.SmallIntegerField(choices=[(1, '显示'), (2, '隐藏')], default=1, verbose_name='页面展示')),
                ('qct_name', models.CharField(max_length=15, verbose_name='求助问题')),
                ('qct_method', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('bct_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show_idea.BigClassTheme', verbose_name='对应的大类主题ID')),
            ],
            options={
                'verbose_name': '3-咨询问题',
                'verbose_name_plural': '3-咨询问题',
            },
        ),
        migrations.CreateModel(
            name='SubClassTheme',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20, verbose_name='创建人')),
                ('updator', models.CharField(default='not', max_length=20, verbose_name='修改人')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit_timestamp', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_show', models.SmallIntegerField(choices=[(1, '显示'), (2, '隐藏')], default=1, verbose_name='页面展示')),
                ('sct_name', models.CharField(max_length=15, verbose_name='子类主题名')),
                ('sct_describe', models.TextField(default='此子类主题暂无描述', max_length=500, verbose_name='子主题描述')),
                ('bct_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show_idea.BigClassTheme', verbose_name='对应的大类主题ID')),
            ],
            options={
                'verbose_name': '2-子类主题',
                'verbose_name_plural': '2-子类主题',
            },
        ),
        migrations.AddField(
            model_name='questioncalsstheme',
            name='sct_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show_idea.SubClassTheme', verbose_name='对应的子类主题ID'),
        ),
    ]
