# Generated by Django 2.0 on 2019-08-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show_idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncalsstheme',
            name='bct_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_idea.BigClassTheme', verbose_name='对应的大类主题ID'),
        ),
        migrations.AlterField(
            model_name='questioncalsstheme',
            name='sct_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_idea.SubClassTheme', verbose_name='对应的子类主题ID'),
        ),
        migrations.AlterField(
            model_name='subclasstheme',
            name='bct_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_idea.BigClassTheme', verbose_name='对应的大类主题ID'),
        ),
    ]
