# Generated by Django 2.0 on 2019-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_idea', '0002_auto_20190826_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigclasstheme',
            name='bct_name',
            field=models.CharField(max_length=32, verbose_name='大类主题名'),
        ),
        migrations.AlterField(
            model_name='questioncalsstheme',
            name='qct_name',
            field=models.CharField(max_length=128, verbose_name='求助问题'),
        ),
        migrations.AlterField(
            model_name='subclasstheme',
            name='sct_name',
            field=models.CharField(max_length=32, verbose_name='子类主题名'),
        ),
    ]
