# Generated by Django 2.0 on 2019-08-27 12:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_idea', '0003_auto_20190826_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncalsstheme',
            name='qct_comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='暂无内容', null=True, verbose_name='内部评语指导'),
        ),
    ]
