# Generated by Django 2.0 on 2019-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_idea', '0004_auto_20190827_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncalsstheme',
            name='is_effective',
            field=models.SmallIntegerField(choices=[(1, '生效中'), (2, '已失效')], default=1, verbose_name='当前状态'),
        ),
    ]
