# Generated by Django 2.0 on 2019-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_idea', '0005_questioncalsstheme_is_effective'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncalsstheme',
            name='visit_count',
            field=models.BigIntegerField(default=0, verbose_name='文章访问量'),
        ),
    ]
