# Generated by Django 2.0 on 2019-08-29 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_idea', '0006_questioncalsstheme_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncalsstheme',
            name='active_endtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0), verbose_name='结束时间'),
        ),
    ]
