# Generated by Django 2.0 on 2019-09-02 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_idea', '0008_auto_20190902_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigclasstheme',
            name='last_edit_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 15, 0, 16, 371829), verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='questioncalsstheme',
            name='last_edit_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 15, 0, 16, 371829), verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='subclasstheme',
            name='last_edit_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 15, 0, 16, 371829), verbose_name='最后修改时间'),
        ),
    ]
