# Generated by Django 2.0 on 2019-09-03 15:21

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show_idea', '0010_auto_20190902_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20, verbose_name='创建人')),
                ('updator', models.CharField(default='not', max_length=20, verbose_name='修改人')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit_timestamp', models.DateTimeField(default=datetime.datetime(2019, 9, 3, 15, 21, 4, 589317), verbose_name='最后修改时间')),
                ('is_show', models.SmallIntegerField(choices=[(1, '显示'), (2, '隐藏')], default=1, verbose_name='页面展示')),
                ('is_popular', models.SmallIntegerField(choices=[(1, '一般问题'), (2, '热门问题')], default=1, verbose_name='是否热门问题')),
                ('is_priority', models.SmallIntegerField(choices=[(1, '1级优先（最高）'), (2, '2级优先'), (3, '3级优先（一般）'), (4, '4级优先'), (5, '5级优先（最低）')], default=3, verbose_name='排序优先级')),
                ('comment_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2048, null=True, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论内容',
                'verbose_name_plural': '评论内容',
            },
        ),
        migrations.AlterField(
            model_name='bigclasstheme',
            name='last_edit_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 15, 21, 4, 589317), verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='questioncalsstheme',
            name='last_edit_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 15, 21, 4, 589317), verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='subclasstheme',
            name='last_edit_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 15, 21, 4, 589317), verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='question_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_idea.QuestionCalssTheme', verbose_name='评论文章'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='reply_question_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='show_idea.QuestionComment', verbose_name='上级评论'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='user_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
    ]
